/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as controllerSol from "./controller.sol";
export type { controllerSol };
import type * as factoriesSol from "./factories.sol";
export type { factoriesSol };
import type * as marketmanagerSol from "./marketmanager.sol";
export type { marketmanagerSol };
import type * as reputationtokenSol from "./reputationtoken.sol";
export type { reputationtokenSol };
