/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as helpersSol from "./helpers.sol";
export type { helpersSol };
import type * as newFetcherSol from "./newFetcher.sol";
export type { newFetcherSol };
import type * as ownedSol from "./owned.sol";
export type { ownedSol };
export type { AggregatorV3Interface } from "./AggregatorV3Interface";
export type { Cash } from "./Cash";
