/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gbcSol from "./GBC.sol";
export type { gbcSol };
import type * as librariesSol from "./libraries.sol";
export type { librariesSol };
import type * as syntheticSol from "./synthetic.sol";
export type { syntheticSol };
