import _$pac from '../../assets/icon/$pac.svg';
import _0xbtc from '../../assets/icon/0xbtc.svg';
import _1inch from '../../assets/icon/1inch.svg';
import _2give from '../../assets/icon/2give.svg';
import _aave from '../../assets/icon/aave.svg';
import _abt from '../../assets/icon/abt.svg';
import _act from '../../assets/icon/act.svg';
import _actn from '../../assets/icon/actn.svg';
import _ada from '../../assets/icon/ada.svg';
import _add from '../../assets/icon/add.svg';
import _adx from '../../assets/icon/adx.svg';
import _ae from '../../assets/icon/ae.svg';
import _aeon from '../../assets/icon/aeon.svg';
import _aeur from '../../assets/icon/aeur.svg';
import _agi from '../../assets/icon/agi.svg';
import _agrs from '../../assets/icon/agrs.svg';
import _aion from '../../assets/icon/aion.svg';
import _algo from '../../assets/icon/algo.svg';
import _amb from '../../assets/icon/amb.svg';
import _amp from '../../assets/icon/amp.svg';
import _ampl from '../../assets/icon/ampl.svg';
import _ankr from '../../assets/icon/ankr.svg';
import _ant from '../../assets/icon/ant.svg';
import _ape from '../../assets/icon/ape.svg';
import _apex from '../../assets/icon/apex.svg';
import _appc from '../../assets/icon/appc.svg';
import _ardr from '../../assets/icon/ardr.svg';
import _arg from '../../assets/icon/arg.svg';
import _ark from '../../assets/icon/ark.svg';
import _arn from '../../assets/icon/arn.svg';
import _arnx from '../../assets/icon/arnx.svg';
import _ary from '../../assets/icon/ary.svg';
import _ast from '../../assets/icon/ast.svg';
import _atlas from '../../assets/icon/atlas.svg';
import _atm from '../../assets/icon/atm.svg';
import _atom from '../../assets/icon/atom.svg';
import _audr from '../../assets/icon/audr.svg';
import _aury from '../../assets/icon/aury.svg';
import _auto from '../../assets/icon/auto.svg';
import _avax from '../../assets/icon/avax.svg';
import _aywa from '../../assets/icon/aywa.svg';
import _bab from '../../assets/icon/bab.svg';
import _bal from '../../assets/icon/bal.svg';
import _band from '../../assets/icon/band.svg';
import _bat from '../../assets/icon/bat.svg';
import _bay from '../../assets/icon/bay.svg';
import _bcbc from '../../assets/icon/bcbc.svg';
import _bcc from '../../assets/icon/bcc.svg';
import _bcd from '../../assets/icon/bcd.svg';
import _bch from '../../assets/icon/bch.svg';
import _bcio from '../../assets/icon/bcio.svg';
import _bcn from '../../assets/icon/bcn.svg';
import _bco from '../../assets/icon/bco.svg';
import _bcpt from '../../assets/icon/bcpt.svg';
import _bdl from '../../assets/icon/bdl.svg';
import _beam from '../../assets/icon/beam.svg';
import _bela from '../../assets/icon/bela.svg';
import _bix from '../../assets/icon/bix.svg';
import _blcn from '../../assets/icon/blcn.svg';
import _blk from '../../assets/icon/blk.svg';
import _block from '../../assets/icon/block.svg';
import _blz from '../../assets/icon/blz.svg';
import _bnb from '../../assets/icon/bnb.svg';
import _bnt from '../../assets/icon/bnt.svg';
import _bnty from '../../assets/icon/bnty.svg';
import _booty from '../../assets/icon/booty.svg';
import _bos from '../../assets/icon/bos.svg';
import _bpt from '../../assets/icon/bpt.svg';
import _bq from '../../assets/icon/bq.svg';
import _brd from '../../assets/icon/brd.svg';
import _bsd from '../../assets/icon/bsd.svg';
import _bsv from '../../assets/icon/bsv.svg';
import _btc from '../../assets/icon/btc.svg';
import _btcd from '../../assets/icon/btcd.svg';
import _btch from '../../assets/icon/btch.svg';
import _btcp from '../../assets/icon/btcp.svg';
import _btcz from '../../assets/icon/btcz.svg';
import _btdx from '../../assets/icon/btdx.svg';
import _btg from '../../assets/icon/btg.svg';
import _btm from '../../assets/icon/btm.svg';
import _bts from '../../assets/icon/bts.svg';
import _btt from '../../assets/icon/btt.svg';
import _btx from '../../assets/icon/btx.svg';
import _burst from '../../assets/icon/burst.svg';
import _bze from '../../assets/icon/bze.svg';
import _call from '../../assets/icon/call.svg';
import _cc from '../../assets/icon/cc.svg';
import _cdn from '../../assets/icon/cdn.svg';
import _cdt from '../../assets/icon/cdt.svg';
import _cenz from '../../assets/icon/cenz.svg';
import _chain from '../../assets/icon/chain.svg';
import _chat from '../../assets/icon/chat.svg';
import _chips from '../../assets/icon/chips.svg';
import _chsb from '../../assets/icon/chsb.svg';
import _chz from '../../assets/icon/chz.svg';
import _cix from '../../assets/icon/cix.svg';
import _clam from '../../assets/icon/clam.svg';
import _cloak from '../../assets/icon/cloak.svg';
import _cmm from '../../assets/icon/cmm.svg';
import _cmt from '../../assets/icon/cmt.svg';
import _cnd from '../../assets/icon/cnd.svg';
import _cnx from '../../assets/icon/cnx.svg';
import _cny from '../../assets/icon/cny.svg';
import _cob from '../../assets/icon/cob.svg';
import _colx from '../../assets/icon/colx.svg';
import _comp from '../../assets/icon/comp.svg';
import _coqui from '../../assets/icon/coqui.svg';
import _cred from '../../assets/icon/cred.svg';
import _crpt from '../../assets/icon/crpt.svg';
import _crv from '../../assets/icon/crv.svg';
import _crw from '../../assets/icon/crw.svg';
import _cs from '../../assets/icon/cs.svg';
import _ctr from '../../assets/icon/ctr.svg';
import _ctxc from '../../assets/icon/ctxc.svg';
import _cvc from '../../assets/icon/cvc.svg';
import _d from '../../assets/icon/d.svg';
import _dai from '../../assets/icon/dai.svg';
import _dash from '../../assets/icon/dash.svg';
import _dat from '../../assets/icon/dat.svg';
import _data from '../../assets/icon/data.svg';
import _dbc from '../../assets/icon/dbc.svg';
import _dcn from '../../assets/icon/dcn.svg';
import _dcr from '../../assets/icon/dcr.svg';
import _deez from '../../assets/icon/deez.svg';
import _dent from '../../assets/icon/dent.svg';
import _dew from '../../assets/icon/dew.svg';
import _dgb from '../../assets/icon/dgb.svg';
import _dgd from '../../assets/icon/dgd.svg';
import _dlt from '../../assets/icon/dlt.svg';
import _dnt from '../../assets/icon/dnt.svg';
import _dock from '../../assets/icon/dock.svg';
import _doge from '../../assets/icon/doge.svg';
import _dot from '../../assets/icon/dot.svg';
import _drgn from '../../assets/icon/drgn.svg';
import _drop from '../../assets/icon/drop.svg';
import _dta from '../../assets/icon/dta.svg';
import _dth from '../../assets/icon/dth.svg';
import _dtr from '../../assets/icon/dtr.svg';
import _ebst from '../../assets/icon/ebst.svg';
import _eca from '../../assets/icon/eca.svg';
import _edg from '../../assets/icon/edg.svg';
import _edo from '../../assets/icon/edo.svg';
import _edoge from '../../assets/icon/edoge.svg';
import _ela from '../../assets/icon/ela.svg';
import _elec from '../../assets/icon/elec.svg';
import _elf from '../../assets/icon/elf.svg';
import _elix from '../../assets/icon/elix.svg';
import _ella from '../../assets/icon/ella.svg';
import _emb from '../../assets/icon/emb.svg';
import _emc from '../../assets/icon/emc.svg';
import _emc2 from '../../assets/icon/emc2.svg';
import _eng from '../../assets/icon/eng.svg';
import _enj from '../../assets/icon/enj.svg';
import _entrp from '../../assets/icon/entrp.svg';
import _eon from '../../assets/icon/eon.svg';
import _eop from '../../assets/icon/eop.svg';
import _eos from '../../assets/icon/eos.svg';
import _eqli from '../../assets/icon/eqli.svg';
import _equa from '../../assets/icon/equa.svg';
import _etc from '../../assets/icon/etc.svg';
import _eth from '../../assets/icon/eth.svg';
import _ethos from '../../assets/icon/ethos.svg';
import _etn from '../../assets/icon/etn.svg';
import _etp from '../../assets/icon/etp.svg';
import _eur from '../../assets/icon/eur.svg';
import _evx from '../../assets/icon/evx.svg';
import _exmo from '../../assets/icon/exmo.svg';
import _exp from '../../assets/icon/exp.svg';
import _fair from '../../assets/icon/fair.svg';
import _fct from '../../assets/icon/fct.svg';
import _fida from '../../assets/icon/fida.svg';
import _fil from '../../assets/icon/fil.svg';
import _fjc from '../../assets/icon/fjc.svg';
import _fldc from '../../assets/icon/fldc.svg';
import _flo from '../../assets/icon/flo.svg';
import _flux from '../../assets/icon/flux.svg';
import _frax from '../../assets/icon/frax-frax-logo.svg';
import _fsn from '../../assets/icon/fsn.svg';
import _ftc from '../../assets/icon/ftc.svg';
import _fuel from '../../assets/icon/fuel.svg';
import _fun from '../../assets/icon/fun.svg';
import _game from '../../assets/icon/game.svg';
import _gas from '../../assets/icon/gas.svg';
import _gbp from '../../assets/icon/gbp.svg';
import _gbx from '../../assets/icon/gbx.svg';
import _gbyte from '../../assets/icon/gbyte.svg';
import _generic from '../../assets/icon/generic.svg';
import _gin from '../../assets/icon/gin.svg';
import _glxt from '../../assets/icon/glxt.svg';
import _gmr from '../../assets/icon/gmr.svg';
import _gmt from '../../assets/icon/gmt.svg';
import _gno from '../../assets/icon/gno.svg';
import _gnt from '../../assets/icon/gnt.svg';
import _gold from '../../assets/icon/gold.svg';
import _grc from '../../assets/icon/grc.svg';
import _grin from '../../assets/icon/grin.svg';
import _grs from '../../assets/icon/grs.svg';
import _grt from '../../assets/icon/grt.svg';
import _gsc from '../../assets/icon/gsc.svg';
import _gto from '../../assets/icon/gto.svg';
import _gup from '../../assets/icon/gup.svg';
import _gusd from '../../assets/icon/gusd.svg';
import _gvt from '../../assets/icon/gvt.svg';
import _gxs from '../../assets/icon/gxs.svg';
import _gzr from '../../assets/icon/gzr.svg';
import _hight from '../../assets/icon/hight.svg';
import _hns from '../../assets/icon/hns.svg';
import _hodl from '../../assets/icon/hodl.svg';
import _hot from '../../assets/icon/hot.svg';
import _hpb from '../../assets/icon/hpb.svg';
import _hsr from '../../assets/icon/hsr.svg';
import _ht from '../../assets/icon/ht.svg';
import _html from '../../assets/icon/html.svg';
import _huc from '../../assets/icon/huc.svg';
import _husd from '../../assets/icon/husd.svg';
import _hush from '../../assets/icon/hush.svg';
import _icn from '../../assets/icon/icn.svg';
import _icp from '../../assets/icon/icp.svg';
import _icx from '../../assets/icon/icx.svg';
import _ignis from '../../assets/icon/ignis.svg';
import _ilk from '../../assets/icon/ilk.svg';
import _ink from '../../assets/icon/ink.svg';
import _ins from '../../assets/icon/ins.svg';
import _ion from '../../assets/icon/ion.svg';
import _iop from '../../assets/icon/iop.svg';
import _iost from '../../assets/icon/iost.svg';
import _iotx from '../../assets/icon/iotx.svg';
import _iq from '../../assets/icon/iq.svg';
import _itc from '../../assets/icon/itc.svg';
import _jnt from '../../assets/icon/jnt.svg';
import _jpy from '../../assets/icon/jpy.svg';
import _kcs from '../../assets/icon/kcs.svg';
import _kin from '../../assets/icon/kin.svg';
import _klown from '../../assets/icon/klown.svg';
import _kmd from '../../assets/icon/kmd.svg';
import _knc from '../../assets/icon/knc.svg';
import _krb from '../../assets/icon/krb.svg';
import _ksm from '../../assets/icon/ksm.svg';
import _lbc from '../../assets/icon/lbc.svg';
import _lend from '../../assets/icon/lend.svg';
import _leo from '../../assets/icon/leo.svg';
import _link from '../../assets/icon/link.svg';
import _lkk from '../../assets/icon/lkk.svg';
import _loom from '../../assets/icon/loom.svg';
import _lpt from '../../assets/icon/lpt.svg';
import _lrc from '../../assets/icon/lrc.svg';
import _lsk from '../../assets/icon/lsk.svg';
import _ltc from '../../assets/icon/ltc.svg';
import _lun from '../../assets/icon/lun.svg';
import _maid from '../../assets/icon/maid.svg';
import _mana from '../../assets/icon/mana.svg';
import _matic from '../../assets/icon/matic.svg';
import _max from '../../assets/icon/max.svg';
import _mcap from '../../assets/icon/mcap.svg';
import _mco from '../../assets/icon/mco.svg';
import _mda from '../../assets/icon/mda.svg';
import _mds from '../../assets/icon/mds.svg';
import _med from '../../assets/icon/med.svg';
import _meetone from '../../assets/icon/meetone.svg';
import _mft from '../../assets/icon/mft.svg';
import _miota from '../../assets/icon/miota.svg';
import _mith from '../../assets/icon/mith.svg';
import _mkr from '../../assets/icon/mkr.svg';
import _mln from '../../assets/icon/mln.svg';
import _mnx from '../../assets/icon/mnx.svg';
import _mnz from '../../assets/icon/mnz.svg';
import _moac from '../../assets/icon/moac.svg';
import _mod from '../../assets/icon/mod.svg';
import _mona from '../../assets/icon/mona.svg';
import _msr from '../../assets/icon/msr.svg';
import _mth from '../../assets/icon/mth.svg';
import _mtl from '../../assets/icon/mtl.svg';
import _music from '../../assets/icon/music.svg';
import _mzc from '../../assets/icon/mzc.svg';
import _nano from '../../assets/icon/nano.svg';
import _nas from '../../assets/icon/nas.svg';
import _nav from '../../assets/icon/nav.svg';
import _ncash from '../../assets/icon/ncash.svg';
import _ndz from '../../assets/icon/ndz.svg';
import _nebl from '../../assets/icon/nebl.svg';
import _neo from '../../assets/icon/neo.svg';
import _neos from '../../assets/icon/neos.svg';
import _neu from '../../assets/icon/neu.svg';
import _nexo from '../../assets/icon/nexo.svg';
import _ngc from '../../assets/icon/ngc.svg';
import _nio from '../../assets/icon/nio.svg';
import _nkn from '../../assets/icon/nkn.svg';
import _nlc2 from '../../assets/icon/nlc2.svg';
import _nlg from '../../assets/icon/nlg.svg';
import _nmc from '../../assets/icon/nmc.svg';
import _nmr from '../../assets/icon/nmr.svg';
import _npxs from '../../assets/icon/npxs.svg';
import _ntbc from '../../assets/icon/ntbc.svg';
import _nuls from '../../assets/icon/nuls.svg';
import _nxs from '../../assets/icon/nxs.svg';
import _nxt from '../../assets/icon/nxt.svg';
import _oax from '../../assets/icon/oax.svg';
import _ok from '../../assets/icon/ok.svg';
import _omg from '../../assets/icon/omg.svg';
import _omni from '../../assets/icon/omni.svg';
import _one from '../../assets/icon/one.svg';
import _ong from '../../assets/icon/ong.svg';
import _ont from '../../assets/icon/ont.svg';
import _oot from '../../assets/icon/oot.svg';
import _ost from '../../assets/icon/ost.svg';
import _ox from '../../assets/icon/ox.svg';
import _oxt from '../../assets/icon/oxt.svg';
import _oxy from '../../assets/icon/oxy.svg';
import _part from '../../assets/icon/part.svg';
import _pasc from '../../assets/icon/pasc.svg';
import _pasl from '../../assets/icon/pasl.svg';
import _pax from '../../assets/icon/pax.svg';
import _paxg from '../../assets/icon/paxg.svg';
import _pay from '../../assets/icon/pay.svg';
import _payx from '../../assets/icon/payx.svg';
import _pink from '../../assets/icon/pink.svg';
import _pirl from '../../assets/icon/pirl.svg';
import _pivx from '../../assets/icon/pivx.svg';
import _plr from '../../assets/icon/plr.svg';
import _poa from '../../assets/icon/poa.svg';
import _poe from '../../assets/icon/poe.svg';
import _polis from '../../assets/icon/polis.svg';
import _poly from '../../assets/icon/poly.svg';
import _pot from '../../assets/icon/pot.svg';
import _powr from '../../assets/icon/powr.svg';
import _ppc from '../../assets/icon/ppc.svg';
import _ppp from '../../assets/icon/ppp.svg';
import _ppt from '../../assets/icon/ppt.svg';
import _pre from '../../assets/icon/pre.svg';
import _prl from '../../assets/icon/prl.svg';
import _pungo from '../../assets/icon/pungo.svg';
import _pura from '../../assets/icon/pura.svg';
import _qash from '../../assets/icon/qash.svg';
import _qiwi from '../../assets/icon/qiwi.svg';
import _qlc from '../../assets/icon/qlc.svg';
import _qnt from '../../assets/icon/qnt.svg';
import _qrl from '../../assets/icon/qrl.svg';
import _qsp from '../../assets/icon/qsp.svg';
import _qtum from '../../assets/icon/qtum.svg';
import _r from '../../assets/icon/r.svg';
import _rads from '../../assets/icon/rads.svg';
import _rap from '../../assets/icon/rap.svg';
import _ray from '../../assets/icon/ray.svg';
import _rcn from '../../assets/icon/rcn.svg';
import _rdd from '../../assets/icon/rdd.svg';
import _rdn from '../../assets/icon/rdn.svg';
import _ren from '../../assets/icon/ren.svg';
import _rep from '../../assets/icon/rep.svg';
import _repv2 from '../../assets/icon/repv2.svg';
import _req from '../../assets/icon/req.svg';
import _rhoc from '../../assets/icon/rhoc.svg';
import _ric from '../../assets/icon/ric.svg';
import _rise from '../../assets/icon/rise.svg';
import _rlc from '../../assets/icon/rlc.svg';
import _rpx from '../../assets/icon/rpx.svg';
import _rub from '../../assets/icon/rub.svg';
import _rvn from '../../assets/icon/rvn.svg';
import _ryo from '../../assets/icon/ryo.svg';
import _safe from '../../assets/icon/safe.svg';
import _safemoon from '../../assets/icon/safemoon.svg';
import _sai from '../../assets/icon/sai.svg';
import _salt from '../../assets/icon/salt.svg';
import _san from '../../assets/icon/san.svg';
import _sand from '../../assets/icon/sand.svg';
import _sbd from '../../assets/icon/sbd.svg';
import _sberbank from '../../assets/icon/sberbank.svg';
import _sc from '../../assets/icon/sc.svg';
import _ser from '../../assets/icon/ser.svg';
import _shift from '../../assets/icon/shift.svg';
import _sib from '../../assets/icon/sib.svg';
import _sin from '../../assets/icon/sin.svg';
import _skl from '../../assets/icon/skl.svg';
import _sky from '../../assets/icon/sky.svg';
import _slr from '../../assets/icon/slr.svg';
import _sls from '../../assets/icon/sls.svg';
import _smart from '../../assets/icon/smart.svg';
import _sngls from '../../assets/icon/sngls.svg';
import _snm from '../../assets/icon/snm.svg';
import _snt from '../../assets/icon/snt.svg';
import _snx from '../../assets/icon/snx.svg';
import _soc from '../../assets/icon/soc.svg';
import _sol from '../../assets/icon/sol.svg';
import _spacehbit from '../../assets/icon/spacehbit.svg';
import _spank from '../../assets/icon/spank.svg';
import _sphtx from '../../assets/icon/sphtx.svg';
import _srn from '../../assets/icon/srn.svg';
import _stak from '../../assets/icon/stak.svg';
import _start from '../../assets/icon/start.svg';
import _steem from '../../assets/icon/steem.svg';
import _storj from '../../assets/icon/storj.svg';
import _storm from '../../assets/icon/storm.svg';
import _stox from '../../assets/icon/stox.svg';
import _stq from '../../assets/icon/stq.svg';
import _strat from '../../assets/icon/strat.svg';
import _stx from '../../assets/icon/stx.svg';
import _sub from '../../assets/icon/sub.svg';
import _sumo from '../../assets/icon/sumo.svg';
import _sushi from '../../assets/icon/sushi.svg';
import _sys from '../../assets/icon/sys.svg';
import _taas from '../../assets/icon/taas.svg';
import _tau from '../../assets/icon/tau.svg';
import _tbx from '../../assets/icon/tbx.svg';
import _tel from '../../assets/icon/tel.svg';
import _ten from '../../assets/icon/ten.svg';
import _tern from '../../assets/icon/tern.svg';
import _tgch from '../../assets/icon/tgch.svg';
import _theta from '../../assets/icon/theta.svg';
import _tix from '../../assets/icon/tix.svg';
import _tkn from '../../assets/icon/tkn.svg';
import _tks from '../../assets/icon/tks.svg';
import _tnb from '../../assets/icon/tnb.svg';
import _tnc from '../../assets/icon/tnc.svg';
import _tnt from '../../assets/icon/tnt.svg';
import _tomo from '../../assets/icon/tomo.svg';
import _tpay from '../../assets/icon/tpay.svg';
import _trig from '../../assets/icon/trig.svg';
import _trtl from '../../assets/icon/trtl.svg';
import _trx from '../../assets/icon/trx.svg';
import _tusd from '../../assets/icon/tusd.svg';
import _tzc from '../../assets/icon/tzc.svg';
import _ubq from '../../assets/icon/ubq.svg';
import _uma from '../../assets/icon/uma.svg';
import _uni from '../../assets/icon/uni.svg';
import _unity from '../../assets/icon/unity.svg';
import _usd from '../../assets/icon/usd.svg';
import _usdc from '../../assets/icon/usdc.svg';
import _usdt from '../../assets/icon/usdt.svg';
import _utk from '../../assets/icon/utk.svg';
import _veri from '../../assets/icon/veri.svg';
import _vet from '../../assets/icon/vet.svg';
import _via from '../../assets/icon/via.svg';
import _vib from '../../assets/icon/vib.svg';
import _vibe from '../../assets/icon/vibe.svg';
import _vivo from '../../assets/icon/vivo.svg';
import _vrc from '../../assets/icon/vrc.svg';
import _vrsc from '../../assets/icon/vrsc.svg';
import _vtc from '../../assets/icon/vtc.svg';
import _vtho from '../../assets/icon/vtho.svg';
import _wabi from '../../assets/icon/wabi.svg';
import _wan from '../../assets/icon/wan.svg';
import _waves from '../../assets/icon/waves.svg';
import _wax from '../../assets/icon/wax.svg';
import _wbtc from '../../assets/icon/wbtc.svg';
import _wgr from '../../assets/icon/wgr.svg';
import _wicc from '../../assets/icon/wicc.svg';
import _wings from '../../assets/icon/wings.svg';
import _wpr from '../../assets/icon/wpr.svg';
import _wtc from '../../assets/icon/wtc.svg';
import _x from '../../assets/icon/x.svg';
import _xas from '../../assets/icon/xas.svg';
import _xbc from '../../assets/icon/xbc.svg';
import _xbp from '../../assets/icon/xbp.svg';
import _xby from '../../assets/icon/xby.svg';
import _xcp from '../../assets/icon/xcp.svg';
import _xdn from '../../assets/icon/xdn.svg';
import _xem from '../../assets/icon/xem.svg';
import _xin from '../../assets/icon/xin.svg';
import _xlm from '../../assets/icon/xlm.svg';
import _xmcc from '../../assets/icon/xmcc.svg';
import _xmg from '../../assets/icon/xmg.svg';
import _xmo from '../../assets/icon/xmo.svg';
import _xmr from '../../assets/icon/xmr.svg';
import _xmy from '../../assets/icon/xmy.svg';
import _xp from '../../assets/icon/xp.svg';
import _xpa from '../../assets/icon/xpa.svg';
import _xpm from '../../assets/icon/xpm.svg';
import _xpr from '../../assets/icon/xpr.svg';
import _xrp from '../../assets/icon/xrp.svg';
import _xsg from '../../assets/icon/xsg.svg';
import _xtz from '../../assets/icon/xtz.svg';
import _xuc from '../../assets/icon/xuc.svg';
import _xvc from '../../assets/icon/xvc.svg';
import _xvg from '../../assets/icon/xvg.svg';
import _xzc from '../../assets/icon/xzc.svg';
import _yfi from '../../assets/icon/yfi.svg';
import _yoyow from '../../assets/icon/yoyow.svg';
import _zcl from '../../assets/icon/zcl.svg';
import _zec from '../../assets/icon/zec.svg';
import _zel from '../../assets/icon/zel.svg';
import _zen from '../../assets/icon/zen.svg';
import _zest from '../../assets/icon/zest.svg';
import _zil from '../../assets/icon/zil.svg';
import _zilla from '../../assets/icon/zilla.svg';
import _zrx from '../../assets/icon/zrx.svg';

export const $pac = _$pac;
export const xbtc = _0xbtc;
export const inch = _1inch;
export const give = _2give;
export const aave = _aave;
export const abt = _abt;
export const act = _act;
export const actn = _actn;
export const ada = _ada;
export const add = _add;
export const adx = _adx;
export const ae = _ae;
export const aeon = _aeon;
export const aeur = _aeur;
export const agi = _agi;
export const agrs = _agrs;
export const aion = _aion;
export const algo = _algo;
export const amb = _amb;
export const amp = _amp;
export const ampl = _ampl;
export const ankr = _ankr;
export const ant = _ant;
export const ape = _ape;
export const apex = _apex;
export const appc = _appc;
export const ardr = _ardr;
export const arg = _arg;
export const ark = _ark;
export const arn = _arn;
export const arnx = _arnx;
export const ary = _ary;
export const ast = _ast;
export const atlas = _atlas;
export const atm = _atm;
export const atom = _atom;
export const audr = _audr;
export const aury = _aury;
export const auto = _auto;
export const avax = _avax;
export const aywa = _aywa;
export const bab = _bab;
export const bal = _bal;
export const band = _band;
export const bat = _bat;
export const bay = _bay;
export const bcbc = _bcbc;
export const bcc = _bcc;
export const bcd = _bcd;
export const bch = _bch;
export const bcio = _bcio;
export const bcn = _bcn;
export const bco = _bco;
export const bcpt = _bcpt;
export const bdl = _bdl;
export const beam = _beam;
export const bela = _bela;
export const bix = _bix;
export const blcn = _blcn;
export const blk = _blk;
export const block = _block;
export const blz = _blz;
export const bnb = _bnb;
export const bnt = _bnt;
export const bnty = _bnty;
export const booty = _booty;
export const bos = _bos;
export const bpt = _bpt;
export const bq = _bq;
export const brd = _brd;
export const bsd = _bsd;
export const bsv = _bsv;
export const btc = _btc;
export const btcd = _btcd;
export const btch = _btch;
export const btcp = _btcp;
export const btcz = _btcz;
export const btdx = _btdx;
export const btg = _btg;
export const btm = _btm;
export const bts = _bts;
export const btt = _btt;
export const btx = _btx;
export const burst = _burst;
export const bze = _bze;
export const call = _call;
export const cc = _cc;
export const cdn = _cdn;
export const cdt = _cdt;
export const cenz = _cenz;
export const chain = _chain;
export const chat = _chat;
export const chips = _chips;
export const chsb = _chsb;
export const chz = _chz;
export const cix = _cix;
export const clam = _clam;
export const cloak = _cloak;
export const cmm = _cmm;
export const cmt = _cmt;
export const cnd = _cnd;
export const cnx = _cnx;
export const cny = _cny;
export const cob = _cob;
export const colx = _colx;
export const comp = _comp;
export const coqui = _coqui;
export const cred = _cred;
export const crpt = _crpt;
export const crv = _crv;
export const crw = _crw;
export const cs = _cs;
export const ctr = _ctr;
export const ctxc = _ctxc;
export const cvc = _cvc;
export const d = _d;
export const dai = _dai;
export const dash = _dash;
export const dat = _dat;
export const data = _data;
export const dbc = _dbc;
export const dcn = _dcn;
export const dcr = _dcr;
export const deez = _deez;
export const dent = _dent;
export const dew = _dew;
export const dgb = _dgb;
export const dgd = _dgd;
export const dlt = _dlt;
export const dnt = _dnt;
export const dock = _dock;
export const doge = _doge;
export const dot = _dot;
export const drgn = _drgn;
export const drop = _drop;
export const dta = _dta;
export const dth = _dth;
export const dtr = _dtr;
export const ebst = _ebst;
export const eca = _eca;
export const edg = _edg;
export const edo = _edo;
export const edoge = _edoge;
export const ela = _ela;
export const elec = _elec;
export const elf = _elf;
export const elix = _elix;
export const ella = _ella;
export const emb = _emb;
export const emc = _emc;
export const emc2 = _emc2;
export const eng = _eng;
export const enj = _enj;
export const entrp = _entrp;
export const eon = _eon;
export const eop = _eop;
export const eos = _eos;
export const eqli = _eqli;
export const equa = _equa;
export const etc = _etc;
export const eth = _eth;
export const ethos = _ethos;
export const etn = _etn;
export const etp = _etp;
export const eur = _eur;
export const evx = _evx;
export const exmo = _exmo;
export const exp = _exp;
export const fair = _fair;
export const fct = _fct;
export const fida = _fida;
export const fil = _fil;
export const fjc = _fjc;
export const fldc = _fldc;
export const flo = _flo;
export const flux = _flux;
export const frax = _frax;
export const fsn = _fsn;
export const ftc = _ftc;
export const fuel = _fuel;
export const fun = _fun;
export const game = _game;
export const gas = _gas;
export const gbp = _gbp;
export const gbx = _gbx;
export const gbyte = _gbyte;
export const generic = _generic;
export const gin = _gin;
export const glxt = _glxt;
export const gmr = _gmr;
export const gmt = _gmt;
export const gno = _gno;
export const gnt = _gnt;
export const gold = _gold;
export const grc = _grc;
export const grin = _grin;
export const grs = _grs;
export const grt = _grt;
export const gsc = _gsc;
export const gto = _gto;
export const gup = _gup;
export const gusd = _gusd;
export const gvt = _gvt;
export const gxs = _gxs;
export const gzr = _gzr;
export const hight = _hight;
export const hns = _hns;
export const hodl = _hodl;
export const hot = _hot;
export const hpb = _hpb;
export const hsr = _hsr;
export const ht = _ht;
export const html = _html;
export const huc = _huc;
export const husd = _husd;
export const hush = _hush;
export const icn = _icn;
export const icp = _icp;
export const icx = _icx;
export const ignis = _ignis;
export const ilk = _ilk;
export const ink = _ink;
export const ins = _ins;
export const ion = _ion;
export const iop = _iop;
export const iost = _iost;
export const iotx = _iotx;
export const iq = _iq;
export const itc = _itc;
export const jnt = _jnt;
export const jpy = _jpy;
export const kcs = _kcs;
export const kin = _kin;
export const klown = _klown;
export const kmd = _kmd;
export const knc = _knc;
export const krb = _krb;
export const ksm = _ksm;
export const lbc = _lbc;
export const lend = _lend;
export const leo = _leo;
export const link = _link;
export const lkk = _lkk;
export const loom = _loom;
export const lpt = _lpt;
export const lrc = _lrc;
export const lsk = _lsk;
export const ltc = _ltc;
export const lun = _lun;
export const maid = _maid;
export const mana = _mana;
export const matic = _matic;
export const max = _max;
export const mcap = _mcap;
export const mco = _mco;
export const mda = _mda;
export const mds = _mds;
export const med = _med;
export const meetone = _meetone;
export const mft = _mft;
export const miota = _miota;
export const mith = _mith;
export const mkr = _mkr;
export const mln = _mln;
export const mnx = _mnx;
export const mnz = _mnz;
export const moac = _moac;
export const mod = _mod;
export const mona = _mona;
export const msr = _msr;
export const mth = _mth;
export const mtl = _mtl;
export const music = _music;
export const mzc = _mzc;
export const nano = _nano;
export const nas = _nas;
export const nav = _nav;
export const ncash = _ncash;
export const ndz = _ndz;
export const nebl = _nebl;
export const neo = _neo;
export const neos = _neos;
export const neu = _neu;
export const nexo = _nexo;
export const ngc = _ngc;
export const nio = _nio;
export const nkn = _nkn;
export const nlc2 = _nlc2;
export const nlg = _nlg;
export const nmc = _nmc;
export const nmr = _nmr;
export const npxs = _npxs;
export const ntbc = _ntbc;
export const nuls = _nuls;
export const nxs = _nxs;
export const nxt = _nxt;
export const oax = _oax;
export const ok = _ok;
export const omg = _omg;
export const omni = _omni;
export const one = _one;
export const ong = _ong;
export const ont = _ont;
export const oot = _oot;
export const ost = _ost;
export const ox = _ox;
export const oxt = _oxt;
export const oxy = _oxy;
export const part = _part;
export const pasc = _pasc;
export const pasl = _pasl;
export const pax = _pax;
export const paxg = _paxg;
export const pay = _pay;
export const payx = _payx;
export const pink = _pink;
export const pirl = _pirl;
export const pivx = _pivx;
export const plr = _plr;
export const poa = _poa;
export const poe = _poe;
export const polis = _polis;
export const poly = _poly;
export const pot = _pot;
export const powr = _powr;
export const ppc = _ppc;
export const ppp = _ppp;
export const ppt = _ppt;
export const pre = _pre;
export const prl = _prl;
export const pungo = _pungo;
export const pura = _pura;
export const qash = _qash;
export const qiwi = _qiwi;
export const qlc = _qlc;
export const qnt = _qnt;
export const qrl = _qrl;
export const qsp = _qsp;
export const qtum = _qtum;
export const r = _r;
export const rads = _rads;
export const rap = _rap;
export const ray = _ray;
export const rcn = _rcn;
export const rdd = _rdd;
export const rdn = _rdn;
export const ren = _ren;
export const rep = _rep;
export const repv2 = _repv2;
export const req = _req;
export const rhoc = _rhoc;
export const ric = _ric;
export const rise = _rise;
export const rlc = _rlc;
export const rpx = _rpx;
export const rub = _rub;
export const rvn = _rvn;
export const ryo = _ryo;
export const safe = _safe;
export const safemoon = _safemoon;
export const sai = _sai;
export const salt = _salt;
export const san = _san;
export const sand = _sand;
export const sbd = _sbd;
export const sberbank = _sberbank;
export const sc = _sc;
export const ser = _ser;
export const shift = _shift;
export const sib = _sib;
export const sin = _sin;
export const skl = _skl;
export const sky = _sky;
export const slr = _slr;
export const sls = _sls;
export const smart = _smart;
export const sngls = _sngls;
export const snm = _snm;
export const snt = _snt;
export const snx = _snx;
export const soc = _soc;
export const sol = _sol;
export const spacehbit = _spacehbit;
export const spank = _spank;
export const sphtx = _sphtx;
export const srn = _srn;
export const stak = _stak;
export const start = _start;
export const steem = _steem;
export const storj = _storj;
export const storm = _storm;
export const stox = _stox;
export const stq = _stq;
export const strat = _strat;
export const stx = _stx;
export const sub = _sub;
export const sumo = _sumo;
export const sushi = _sushi;
export const sys = _sys;
export const taas = _taas;
export const tau = _tau;
export const tbx = _tbx;
export const tel = _tel;
export const ten = _ten;
export const tern = _tern;
export const tgch = _tgch;
export const theta = _theta;
export const tix = _tix;
export const tkn = _tkn;
export const tks = _tks;
export const tnb = _tnb;
export const tnc = _tnc;
export const tnt = _tnt;
export const tomo = _tomo;
export const tpay = _tpay;
export const trig = _trig;
export const trtl = _trtl;
export const trx = _trx;
export const tusd = _tusd;
export const tzc = _tzc;
export const ubq = _ubq;
export const uma = _uma;
export const uni = _uni;
export const unity = _unity;
export const usd = _usd;
export const usdc = _usdc;
export const usdt = _usdt;
export const utk = _utk;
export const veri = _veri;
export const vet = _vet;
export const via = _via;
export const vib = _vib;
export const vibe = _vibe;
export const vivo = _vivo;
export const vrc = _vrc;
export const vrsc = _vrsc;
export const vtc = _vtc;
export const vtho = _vtho;
export const wabi = _wabi;
export const wan = _wan;
export const waves = _waves;
export const wax = _wax;
export const wbtc = _wbtc;
export const wgr = _wgr;
export const wicc = _wicc;
export const wings = _wings;
export const wpr = _wpr;
export const wtc = _wtc;
export const x = _x;
export const xas = _xas;
export const xbc = _xbc;
export const xbp = _xbp;
export const xby = _xby;
export const xcp = _xcp;
export const xdn = _xdn;
export const xem = _xem;
export const xin = _xin;
export const xlm = _xlm;
export const xmcc = _xmcc;
export const xmg = _xmg;
export const xmo = _xmo;
export const xmr = _xmr;
export const xmy = _xmy;
export const xp = _xp;
export const xpa = _xpa;
export const xpm = _xpm;
export const xpr = _xpr;
export const xrp = _xrp;
export const xsg = _xsg;
export const xtz = _xtz;
export const xuc = _xuc;
export const xvc = _xvc;
export const xvg = _xvg;
export const xzc = _xzc;
export const yfi = _yfi;
export const yoyow = _yoyow;
export const zcl = _zcl;
export const zec = _zec;
export const zel = _zel;
export const zen = _zen;
export const zest = _zest;
export const zil = _zil;
export const zilla = _zilla;
export const zrx = _zrx;