/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CreditLine } from "./CreditLine";
export type { Instrument } from "./Instrument";
export type { MockBorrowerContract } from "./MockBorrowerContract";
export type { Proxy } from "./Proxy";
