/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as gbcSol from "./GBC.sol";
export * as librariesSol from "./libraries.sol";
export * as syntheticSol from "./synthetic.sol";
