/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SyntheticZCBPool__factory } from "./SyntheticZCBPool__factory";
export { SyntheticZCBPoolFactory__factory } from "./SyntheticZCBPoolFactory__factory";
